// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5505.Francis.subsystems;


import org.usfirst.frc5505.Francis.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
import com.revrobotics.CANSparkMax;
import com.revrobotics.CANSparkMaxLowLevel.MotorType;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.DoubleSolenoid.Value;
import edu.wpi.first.wpilibj.GenericHID.RumbleType;
import edu.wpi.first.wpilibj.Ultrasonic.Unit;
import edu.wpi.first.wpilibj.DriverStation;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Ultrasonic;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class drive extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS


    private CANSparkMax sparkMAX1;
    private CANSparkMax sparkMAX2;
    private CANSparkMax sparkMAX3;
    private CANSparkMax sparkMAX4;
    private RobotDrive robotDrive41;
    private DoubleSolenoid doubleSolenoid1;
    private Ultrasonic leftUltra = new Ultrasonic(1, 0);
    private Ultrasonic rightUltra = new Ultrasonic(3, 2);

    public boolean isDriverControlMode = true;

    public double x1 = 0;
    public double x2 = 0;
    public double y1 = 0;
    public double y2 = 0;
    public double lineAngle = 0;  
    public double lineLength = 0;
    public boolean areThereLines = false;


    public drive() {

        sparkMAX1 = new CANSparkMax(16, MotorType.kBrushless);
        
        
        
        sparkMAX2 = new CANSparkMax(1, MotorType.kBrushless);
        
        
        
        sparkMAX3 = new CANSparkMax(2, MotorType.kBrushless);
        
        
        
        sparkMAX4 = new CANSparkMax(3, MotorType.kBrushless);
        
        
        
        robotDrive41 = new RobotDrive(sparkMAX1, sparkMAX2, sparkMAX3, sparkMAX4);
        
        robotDrive41.setSafetyEnabled(false);
        robotDrive41.setExpiration(0.1);
        robotDrive41.setSensitivity(0.5);
        robotDrive41.setMaxOutput(1.0);

        
        doubleSolenoid1 = new DoubleSolenoid(0, 6, 7);
        addChild("Double Solenoid 1",doubleSolenoid1);
         
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new driveBase());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
        doubleSolenoid1.set(Value.kForward);
        SmartDashboard.putBoolean("Gear", false);
        leftUltra.setAutomaticMode(true);
        //leftUltra.setDistanceUnits(Unit.kInches);
        rightUltra.setAutomaticMode(true);
        //rightUltra.setDistanceUnits(Unit.kInches);
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop
        SmartDashboard.putNumber("Left Ultrasonic", leftUltra.getRangeInches());
        SmartDashboard.putNumber("Right Ultrasonic", rightUltra.getRangeInches());
        checkVision();
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void driveBase(Joystick stick) {
        double reduction = .75;
        if (isDriverControlMode) { 
            robotDrive41.tankDrive(stick.getRawAxis(1) * reduction, stick.getRawAxis(5) * reduction);
        }
        if (DriverStation.getInstance().getMatchTime() > 29 && DriverStation.getInstance().getMatchTime() < 31 && DriverStation.getInstance().isOperatorControl()) {
            stick.setRumble(RumbleType.kLeftRumble, 1);
        } else if (DriverStation.getInstance().getMatchTime() <= 29 && DriverStation.getInstance().isOperatorControl()) {
            stick.setRumble(RumbleType.kLeftRumble, 0);
        }
    }

    public void shift() {
        System.out.println("Started Shift Command");
        if (doubleSolenoid1.get() != Value.kForward) {
            doubleSolenoid1.set(Value.kForward);
            System.out.println("Shifted to Low Gear");
            SmartDashboard.putBoolean("Gear", false);
        } else {
            doubleSolenoid1.set(Value.kReverse);
            System.out.println("Shifted to High Gear");
            SmartDashboard.putBoolean("Gear", true);
        }
    }

    public boolean ultraWallAllign() {
        double turnFactor = .05;
        double speedFactor = .1;
        double maxError = 1;
        double difference = rightUltra.getRangeInches() - leftUltra.getRangeInches();
        if (Math.abs(difference) > maxError) {
            robotDrive41.arcadeDrive(speedFactor, difference * turnFactor);
            return false;
        } else {
            robotDrive41.arcadeDrive(0, 0);
            return true;
        }
    }

    public void returnDriverControl() {
        isDriverControlMode = true;
    }

    public void checkVision() {
        try {
            x1 = NetworkTableInstance.getDefault().getTable("GRIP/horizontalLines").getEntry("x1").getDouble(0);
            x2 = NetworkTableInstance.getDefault().getTable("GRIP/horizontalLines").getEntry("x2").getDouble(0);
            y1 = NetworkTableInstance.getDefault().getTable("GRIP/horizontalLines").getEntry("y1").getDouble(0);
            y2 = NetworkTableInstance.getDefault().getTable("GRIP/horizontalLines").getEntry("y2").getDouble(0); 
            lineAngle = NetworkTableInstance.getDefault().getTable("GRIP/horizontalLines").getEntry("angle").getDouble(0);
            lineLength = NetworkTableInstance.getDefault().getTable("GRIP/horizontalLines").getEntry("length").getDouble(0);
            double xAverage = (x1 + x2) / 2;
            double callibration = 1; //How far left or right the line must be to read offcenter
            if (xAverage < callibration) {
                SmartDashboard.putBoolean("Left", true);
                SmartDashboard.putBoolean("Right", false);
                SmartDashboard.putBoolean("Center", false);
            } else if (xAverage > callibration) {
                SmartDashboard.putBoolean("Left", false);
                SmartDashboard.putBoolean("Right", true);
                SmartDashboard.putBoolean("Center", false);
            } else {
                SmartDashboard.putBoolean("Left", false);
                SmartDashboard.putBoolean("Right", false);
                SmartDashboard.putBoolean("Center", true);
            }
        } catch (Exception e) {
            System.out.println("Line Exception: " + e.getMessage());
        }
    }
}

